/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rushhour;

import java.awt.Color;
import java.awt.Graphics;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Daar375
 */
public class GUI extends javax.swing.JFrame {
private Graphics tableGraphics;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    long inicio;
    long fin;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        StartButton = new javax.swing.JButton();
        gamePanel = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenButton = new javax.swing.JMenuItem();
        ExitButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio = System.currentTimeMillis();
                StartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        FileMenu.setText("File");
        FileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuActionPerformed(evt);
            }
        });

        OpenButton.setText("Open");
        OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButtonActionPerformed(evt);
            }
        });
        FileMenu.add(OpenButton);

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        FileMenu.add(ExitButton);

        jMenuBar2.add(FileMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 944, Short.MAX_VALUE)
                        .addComponent(StartButton))
                    .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuActionPerformed

    }//GEN-LAST:event_FileMenuActionPerformed

    private void OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenButtonActionPerformed
        // TODO add your handling code here:
                   int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_OpenButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
                       System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        tableGraphics = gamePanel.getGraphics();
        Parser parse = new Parser();
        String caso1 = "..\\Casos\\casoFacil1.csv";
        String caso2 = "..\\Casos\\casoFacil2.csv";
        String caso3 = "..\\Casos\\casoFacil3.csv";
        String caso4 = "..\\Casos\\casoInter4.csv";
        String caso5 = "..\\Casos\\casoInter5.csv";
        String caso6 = "..\\Casos\\casoInter6.csv";
        String caso7 = "..\\Casos\\casoDificil7.csv";
        String caso8 = "..\\Casos\\casoDificil8.csv";
        String caso9 = "..\\Casos\\casoDificil9.csv";
        String caso10 = "..\\Casos\\casoMuyDificil10.csv";
        String caso11 = "..\\Casos\\casoMuyDificil11.csv";
        String caso12 = "..\\Casos\\casoMuyDificil12.csv";
        int exit[];
        
        //Seleccionar caso
        String archivo = caso12; 
        
        LinkedList carList = parse.parseFile(archivo); 
        exit = parse.parseExit(archivo);
        
        Puzzle initialPuzzle = new Puzzle(6,carList,exit[0],exit[1],0);
        Astar game = new Astar();
        if(exit[0] == 5){
            DrawGame(initialPuzzle, exit[0]+1, exit[1]);
            DrawGameSequence(game.searchAStar(initialPuzzle), exit[0]+1, exit[1]);
        } else{
            DrawGame(initialPuzzle, exit[0], exit[1]+1);
            DrawGameSequence(game.searchAStar(initialPuzzle), exit[0], exit[1]+1);
        }
    
    }//GEN-LAST:event_StartButtonActionPerformed
    public void DrawGameSequence(ArrayList<Puzzle> squence, int exitx, int exity){
        for (Puzzle puzzle : squence){
            try {
                DrawGame(puzzle, exitx, exity); 
                puzzle.printMatrix(puzzle.getMatrix());
                TimeUnit.MILLISECONDS.sleep(300);
            } catch (InterruptedException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.out.println("Moves: " + squence.size());
        fin = System.currentTimeMillis();
         
        double tiempo = (double) ((fin - inicio));
         
        System.out.println(tiempo +" milisegundos");

    }
    public void DrawGame(Puzzle puzzle,int exitx, int exity){
        
        


        int y = 0;
        int x = 0;
        
        while (y!=6){
            tableGraphics.setColor(Color.DARK_GRAY);

            /*if(y==2){
              tableGraphics.fillRect(63,12+(95*y),665,97);  
*/
            //}else{
            tableGraphics.fillRect(63,12+(95*y),660-90,95);  

            //}
            y++;
        }
        y = 0;
        while(x !=6){
           while(y !=6){
            tableGraphics.setColor(Color.gray);
            tableGraphics.fillRect(65+(95*x),15+(95*y),90,90);  
            y++;
            } 
           y = 0;
           x++;
        }
        y = 0;
        x = 0;
        while(x !=6){
           while(y !=6){
            tableGraphics.setColor(Color.lightGray);
            tableGraphics.fillRect(70+(95*x),20+(95*y),80,80);  
            y++;
            } 
           y = 0;
           x++;
        }  
        
        tableGraphics.setColor(Color.gray);

        tableGraphics.fillRect(65+(95*exitx),15+(95*exity),90,90);  
        tableGraphics.setColor(Color.green);

        tableGraphics.fillRect(70+(95*exitx),20+(95*exity),80,80);  
        
        
        for( Vehicle car : puzzle.cars){
            if(car.type.equals("player")){
               PaintCar(Color.RED,car.posX,car.posY,car.size,car.isHorizontal());

            }else
            PaintCar(Color.BLUE,car.posX,car.posY,car.size,car.isHorizontal());
        }

    }
    

    private void PaintCar(Color color, int xStart , int yStart,int lenght, Boolean horizontal){
           tableGraphics.setColor(color);
           if(horizontal)
           tableGraphics.fillRect(64+(95*xStart),14+(95*yStart),93*(lenght),93); 
           else 
           tableGraphics.fillRect(64+(95*xStart),14+(95*yStart),93,93*(lenght)); 

           //tableGraphics.fillRect(63+(95*xEnd),13+(95*yEnd),95,95);


    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);

            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitButton;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem OpenButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
